## Arewa Data Science Academy
### Deep Learning Cohort1.0

#### Name: Muhammad Ibrahim Isah 
#### Email: muhammadibrahimisah0@gmail.com
#### Title: Week 1 Solution

### Exercises Solution

In [5]:
# Q2. Create a random tensor with shape `(7, 7)`.

import torch 

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.4362, 0.0037, 0.1445, 0.2260, 0.2751, 0.4716, 0.3600],
         [0.0789, 0.4903, 0.2420, 0.7027, 0.7895, 0.2342, 0.0680],
         [0.5828, 0.1443, 0.1643, 0.9561, 0.1665, 0.3389, 0.8608],
         [0.5169, 0.5615, 0.7107, 0.1013, 0.6123, 0.4705, 0.6322],
         [0.1243, 0.6224, 0.3491, 0.0439, 0.8884, 0.4930, 0.6646],
         [0.2483, 0.3835, 0.3385, 0.3346, 0.1466, 0.6180, 0.4066],
         [0.0421, 0.5068, 0.2497, 0.8925, 0.6354, 0.7840, 0.3264]]),
 torch.Size([7, 7]))

In [6]:
# Q 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

Y = torch.rand(size=(1, 7))
Z = torch.matmul(X, Y.T) 
Z, Z.shape


(tensor([[0.5394],
         [0.8404],
         [0.9617],
         [1.1447],
         [1.0279],
         [0.9176],
         [1.2465]]),
 torch.Size([7, 1]))

In [7]:
# Q4. Set the random seed to `0` and do 2 & 3 over again

# Set 0 seed
torch.manual_seed(0)

X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [9]:
# Q6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be som

# Set random seed to 1234
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B



Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))