## Arewa Data Science Academy
### Deep Learning Cohort1.0

#### Name: Muhammad Ibrahim Isah 
#### Email: muhammadibrahimisah0@gmail.com
#### Title: Week 1 Solution

### Exercises Solution

In [5]:
# Q2. Create a random tensor with shape `(7, 7)`.

import torch 

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388],
         [0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399],
         [0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893],
         [0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770],
         [0.4108, 0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189],
         [0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658],
         [0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451, 0.4966]]),
 torch.Size([7, 7]))

In [6]:
# Q 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

Y = torch.rand(size=(1, 7))
Z = torch.matmul(X, Y.T) 
Z, Z.shape


(tensor([[2.1391],
         [2.3548],
         [1.6001],
         [1.9384],
         [1.4356],
         [2.1416],
         [1.7684]]),
 torch.Size([7, 1]))

In [7]:
# Q4. Set the random seed to `0` and do 2 & 3 over again

# Set 0 seed
torch.manual_seed(0)

X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [8]:
# Q6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be som

# Set random seed to 1234
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B



Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))